name: run main.py
permissions:
  contents: write
  packages: write
  actions: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Everyday at 1am
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo Content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

        run: python main.py
          
      - name: commit files
        uses: stefanzweifel/git-auto-commit-action@v5
      #  run: |
      #   git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add -A
      #    git diff-index --quiet HEAD || git commit -a -m "updated logs" --allow-empty
      #    
      #- name: push changes
        #uses: ad-m/github-push-action@v0.6.0
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: main 